### ISSUE TITLE
Hide obvious menu items (noise)

### ISSUE THREAD

**Issue by maialalor** [Anze/KeyCluCask#12]
My eyes get distracted when there is a lot of text on my screen 😵‍💫

I'd like to maintain a personal list of shortcuts that are extremely obvious to me (such as ⌘C Copy, ⌘Z Undo, etc...) and have KeyClu filter them out from the overview.

Any small reduction in the amount of clutter helps me out! 

Thank you for your consideration 😊

**Comment by Anze** [comment]
I've made this live. I't might work not that obvious. Just right click on element and pick action.
When you *hide* element (blue) it would be hidden only for that app.
When you *hide globally* (red) it would be hidden for all apps, based on menu name *and* shortcut. So if name does not match, it would not be hidden. I decide to go this way cause many apps have mentioning what would happen when you ⌘Z, for example Finder can tell it would cancel move file File.ext, and in this case it would not be *globally hidden*.
