### ISSUE TITLE
KeyClu quits on Mac OS Sonoma

### ISSUE THREAD

**Issue by sebnoumea** [Anze/KeyCluCask#20]
I've just installed the app from brew. As soon as the keyboard shortcut is executed the app crashes.

**Comment by Anze** [comment]
Hey sebnoumea,
Can please provide more details, like what app was active or it happens with any app? I cant reproduce issue with Sonoma in VM.

**Comment by sebnoumea** [comment]
Hi,

Just installed the latest update and it still crashes. 
* what app was active or it happens with any app?
Happens with any app. Only works in KeyClu's preferences.
* does KeyClu installed in /Applications?
 yes
* what language or keyboard layout you using?
French, french keyboard layout

**Comment by Anze** [comment]
Thanks for the info. I've checked again, still no issues experienced. Can you please check directories:
- ```~/Library/Application Support/CrashReporter``` for file ```KeyClu_<randomly-generated-uuid>.plist```
- ```~/Library/Logs/DiagnosticReports``` for file ```KeyClu-<date-time>.ips```
and send it to sms[@]tatarenkov.name please if there any? Would be enough 1 file from each dir.

**Comment by sebnoumea** [comment]
Thanks ! 🙂
