### ISSUE TITLE
Add command line trigger for "show shortcuts"

### ISSUE THREAD

**Issue by maialalor** [Anze/KeyCluCask#21]
I started using [skhd](https://github.com/koekeishiya/skhd) as a hotkey manager, but unfortunately it seems to conflict with KeyClu, as the KeyClu shortcuts don't work anymore :(

I think the easiest way to provide support for this setup, as well as many other possible setups, would be to provide a command line trigger, for example:

```
/Applications/KeyClu.app/Contents/MacOS/KeyClu --showShortcuts
```

Then it would be easy to use with skhd, or any other trigger that a user can imagine.

It would be nice of course for the cool Command-based shortcuts to work with skhd, but that could possibly, be too much work, be too hard to solve, or even impossible under macOS. So investigating the specific interaction with skhd sounds like a riskier use of time.

**Comment by Anze** [comment]
I've checked skhd and see not issue with KeyClu. Unless you trying to remap a key to which KeyClu should react. Please provide your .skhdrc for more details.

Please note, KeyClu workflow is different than just react to hotkey, it show window *while* you holding ⌘ key down, when you release it - window would be closed. Also if you press any other key - window would be closed.

**Comment by maialalor** [comment]
I finally got some time to troubleshoot, and it actually is working for me now. I'm not sure what changed on my end... but regardless, it's working! Sorry about the confusion.
