### ISSUE TITLE
[feature request] Option to Redirect to CustomShortcuts App

### ISSUE THREAD

**Issue by wanwindwalker** [Anze/KeyCluCask#25]
CheatSheets has a pencil appear whenever you hover over a shortcut. When you click it, if you have CustomShortcuts installed (custom shortcut manager), it launches it and inputs the name of the shortcut you clicked then lets you rebind it. Could this be added as a feature even if disabled by default? Thanks.

**Comment by Anze** [comment]
I was thinking to make this functionality by myself, but this could be also an option. Would investigate this feature.

**Comment by Anze** [comment]
I've implemented integration with CustomShotcuts, hope you will like it.

**Comment by wanwindwalker** [comment]
> I've implemented integration with CustomShotcuts, hope you will like it.

I love it!
