### ISSUE TITLE
App Icon

### ISSUE THREAD

**Issue by wanwindwalker** [Anze/KeyCluCask#26]
I like customizing my mac icons so I made a more refined rendition of KeyClue's. If you like it you can use it as the default. Here are the files: http://www.mediafire.com/folder/9hztly0kmaj4f68,sedipa0zk4gfljc/shared

**Comment by Anze** [comment]
Thank you! I'll check it.

**Comment by Anze** [comment]
Thank you for your work, I've updated the app's icon.
