### ISSUE TITLE
does not work if sticky keys is enabled

### ISSUE THREAD

**Issue by Fiorefiore** [Anze/KeyCluCask#27]
I can't open the cheat shit by double clicking and holding "command" if i have sticky keys enabled. how can i use this app while maintaining sticky keys active?

**Comment by Anze** [comment]
Hello [Fiorefiore](https://github.com/Fiorefiore), 
as I can see sticky keys are made for people who type slowly, and there should be a time (delay) between keys pressed. At the moment KeyClu is not supporting *sticky keys* natively for activation by pressing command twice. Instead you can switch activation to single press and hold command key and increase delay before activation, this should work, as it required less effort to call a shortcut panel. To hide the panel you would need to press command again 1(2) times to release the command key. It is not the perfect way, but some workaround.
I would note to try to make it work by double pressing the command key, but as I can see it is required to press command key 4 times, which might be not convenient.

**Comment by Fiorefiore** [comment]
Thank you for your fast reply, I really appreciated it! 
I was looking for a way to change shortcut to open KeyClu (such as “command .” ). 
Changing the default shortcut to “hold command” would interfere with the shortcut I use to select an area and take a screenshot (command space), since it would open KeyClu over the page I want to screenshot.
Yesterday I could not find a way to open the app while having stickykey enabled, but after reading your email I tried pressing command 6 times fast and holding it down and it works well. It’s not the most convincente way to open an app, but I’m quite satisfied!
Hope you have a great day, Thank you
Fiore

**Comment by Anze** [comment]
Hey, nice that you found a way to make it work.
As I've mentioned, it is possible to assign other hotkey to activate shortcuts window, here is an example with [skhd](https://github.com/koekeishiya/skhd). You would need to have `.skhdrc` in your home directory. Sample content for the file:
```
cmd + ctrl - a : /Applications/KeyClu.app/Contents/MacOS/KeyClu --show-shortcuts
```
That would trigger to show shortcuts window by pressing `cmd`+`ctrl`+`a`
