### ISSUE TITLE
Startup App

### ISSUE THREAD

**Issue by wakmail** [Anze/KeyCluCask#28]
Make it so that KeyCLU is launched automatically when the computer boots.

**Comment by Anze** [comment]
Hey [wakmail](https://github.com/wakmail),
Actually it has such an option already - `launch at login`. Unfortunately it is available for macOS Ventura and later.
Unfortunately it requires some effort to make it work in Big Sur and Monterey. Still in old macOS versions you can add it manually.
Also in the next release I've already included a button to help find a place where to add an App to `login Items`.
