### ISSUE TITLE
Add delay

### ISSUE THREAD

**Issue by RyanRoberts** [Anze/KeyCluCask#3]
Nice app, thanks for making it!

I find myself accidentally triggering KeyClu quite often, it just flashes up on screen when I don't intend to trigger it. Would you consider adding the option to set a delay before it appears so we can fine tune how soon it appears after triggering?

**Comment by Anze** [comment]
Well, this is discussable thing as it affects how fast you want to see list and way how you need to press ⌘.
There is a tricky part.
Here is how it is done now, just press ⌘ twice:
```Press ⌘ first time -> wait for second ⌘ to be pressed within 0.5 sec```
Here is another example, just press ⌘ twice and hold within time period:
```Press ⌘ first time -> wait for second ⌘ to pressed and hold it for at least 1 sec```
You expecting that behaviour?

**Comment by RyanRoberts** [comment]
Works great! Thanks.
