### ISSUE TITLE
i18n: English language typo in app config panel

### ISSUE THREAD

**Issue by nacengineer** [Anze/KeyCluCask#30]
For General, Visual, and Advanced items Presets is incorrectly spelled as Pressets

**Comment by BramEsposito** [comment]
<img width="832" height="592" alt="Image" src="https://github.com/user-attachments/assets/328dfa34-0609-45a7-a95b-251f88679df6" />

It's still there on 0.31 (27097)

**Comment by Anze** [comment]
Hey [BramEsposito](https://github.com/BramEsposito),
Thanks for the suggestion! This has already been fixed and will be included in the next release.
It would also be great if you could help review the translations and suggest improvements where needed in the [Crowdin project](https://crowdin.com/project/keyclu/).
