### ISSUE TITLE
Disable triple cmd (sticky window)

### ISSUE THREAD

**Issue by sammcj** [Anze/KeyCluCask#32]
It would be great if you could disable the triple cmd sticky window in preferences.

I find it triggers too easily when I'm thinking / hesitating and have my thumb on the cmd key and as there's no native way to remap the trigger I'd like to disable it if possible?

<img width="547" alt="image" src="https://github.com/Anze/KeyCluCask/assets/862951/770503e7-d867-47d5-b858-dcbfc613dab3">

**Comment by Anze** [comment]
Sure, I would include possibility to disable it.

**Comment by sammcj** [comment]
Got the latests update, that's awesome! Thank you so much!
