### ISSUE TITLE
Crashes when using with Firefox 

### ISSUE THREAD

**Issue by tracerbu11et** [Anze/KeyCluCask#39]
Just installed KeyCluCask and when trying to use in Firefox 120.0b3, it causes KeyClu and Firefox to stop responding. Once KeyClu is force quit Firefox becomes responsive again.

Running on Sonoma 14.0 (23A344)

**Comment by Anze** [comment]
Hey [tracerbu11et](https://github.com/tracerbu11et),
I'm sorry to hear that you're experiencing issues with the app. Based on the behavior you've described, it seems like this problem might be related to having a large number of bookmarks. Have you tried enabling the "Limit amount of elements for browsers" option in the Advanced settings?
