### ISSUE TITLE
Function Keys like F13-F19 are not supported in My Shortcuts

### ISSUE THREAD

**Issue by wadjj** [Anze/KeyCluCask#41]
I have a magic keyboard (the previous generation without touch ID), and have set up several hot keys with under-utilized functions keys like F16.
It seems that keyclu can detect the key press in My Shortcuts Settings, but cannot display it (just empty)

**Comment by Anze** [comment]
Hey [wadjj](https://github.com/wadjj), thanks for bringing this issue to my attention. Can you assist me with its resolution? Since it appears that you registered those keys manually, could you kindly send or post an exported file here? This would greatly help me in testing.

**Comment by Anze** [comment]
Hey [wadjj](https://github.com/wadjj),
The issue should be fixed with v0.18 release.
