### ISSUE TITLE
Persistent window not working?

### ISSUE THREAD

**Issue by mike-ward** [Anze/KeyCluCask#43]
Hi,

Maybe I'm doing something wrong but I can't get the persistent window to work. Pressed the command key three times. Nothing happens.

Looks to be enabled int the settings.

<img width="711" alt="image" src="https://github.com/Anze/KeyCluCask/assets/567927/80b6878e-6a10-4be4-a482-9d3a28dc7119">

<img width="248" alt="image" src="https://github.com/Anze/KeyCluCask/assets/567927/5978e9dd-461c-45e3-97cf-758ca7942a65">

**Comment by Anze** [comment]
Hey [mike-ward](https://github.com/mike-ward),
You might need to press it more quickly, the default time between pressed keys should not exceed 0.5 seconds. If you wish to extend that time, you can adjust the settings in Advanced -> Sticky Keys. Keep in mind that this adjustment will also impact the regular window appearing (might be unwanted window appearing during regular actions).

**Comment by mike-ward** [comment]
Tried press three times really fast. Still no joy.

**Comment by Anze** [comment]
Thank for feedback. I will implement some improvements regarding this issue.

**Comment by blimey85** [comment]
Turning it off and back on worked for me as well.

Would it be possible to be able to move the persistent window around the screen? Right now it has a fixed position and that isn't always an ideal location.
