### ISSUE TITLE
[Feature Request] Panel Width Configuration?

### ISSUE THREAD

**Issue by ryanbelisle** [Anze/KeyCluCask#44]
@Anze,

I just download KeyClu and I'm loving the application thus far! Especially how simple it is to just double hit the `cmd` key to bring up the shortcuts.

I do have a suggestion for you to consider that well help the app's readability on large screens. Would it be possible to implement a configuration option to set the desired panel width based on `%` or `px`? For example, give users the opportunity to set the width of the panel to:
- `25%
- `50%`
- `75%`
- etc.
- `1024px`
- and/or define a custom `%` or `px` width?

I have a 49" ultra-widescreen and it's hard to quickly scan/read through the shortcuts because the panel is so wide. I can't see everything in 1 glance. The title of the shortcut and the shortcuts themselves are so far apart it's hard to see the relationship.

Thanks for considering!

**Comment by Anze** [comment]
Hey [ryanbelisle](https://github.com/ryanbelisle),
Thank you for the suggestion. I will certainly implement this.
