### ISSUE TITLE
does not compatiable with finder

### ISSUE THREAD

**Issue by EthanPixar** [Anze/KeyCluCask#45]
↓

**Comment by Anze** [comment]
Finally I've identified the problem. The issue is in Accessibility API. Unfortunately there's currently no definitive solution available for this issue. Also, it appears that other apps are grappling with the same challenge.

**Comment by EthanPixar** [comment]
Appreciate your devotion!! Although it's generally not big a problem and I know little about the code that is related, but I've seen your efforts in making this wonderful app!! Great respect!

**Comment by Anze** [comment]
Hey [EthanPixar](https://github.com/EthanPixar),
I've just checked app on macOS 14 and looks like menu item was removed in that macOS version, but hotkey `⌘ ↓` itself still works.

**Comment by EthanPixar** [comment]
yes, I spot the problem too, a 'hidden keyboard shortcut'
