### ISSUE TITLE
Persistent Panel Activation

### ISSUE THREAD

**Issue by CMWalt** [Anze/KeyCluCask#48]
New user here.

The persistent panel trigger isn't working.

Chip Apple M1 Max
Memory• 64 GB
Startup disk
Macintosh HD
macOS Sonoma 14.2.1

**Comment by CMWalt** [comment]
Thank you. That solved the problem with the Hide and Show. But I see a new issue with the Persistent Panel.

When using multiple monitors, if the panel is on a "smaller" monitor and the app is on a "larger" monitor, the shortcuts don't align to the top of the panel, and some shortcuts are not viewable.

**Comment by Anze** [comment]
Sure, thanks! Could you report this issue in a separate topic and include details like your multi-monitor setup and which one is your main monitor?
