### ISSUE TITLE
[enhancement] Persistent Panel on Multi-monitor Setup

### ISSUE THREAD

**Issue by CMWalt** [Anze/KeyCluCask#49]
When using multiple monitors, if the panel is on a "smaller" monitor and the app is on a "larger" monitor, "sometimes," the shortcuts don't align to the panel's top, and some shortcuts are not viewable.

Larger Monitor = 27" Studio Display
Smaller Monitor = 16" MacBook Pro

Chip Apple M1 Max
macOS Sonoma 14.2.1

---

## Proper

Here, the active app is on the MacBook (Screenshot is of MacBook)
<img width="1728" alt="Screenshot 2024-01-27 at 12 37 02 PM" src="https://github.com/Anze/KeyCluCask/assets/116489828/f94313d4-4b30-4a59-9929-31f920028c61">

## Alignment Issue

Here, the active app is on the Studio Display (Screenshot is of MacBook)
<img width="1728" alt="Screenshot 2024-01-27 at 12 38 52 PM" src="https://github.com/Anze/KeyCluCask/assets/116489828/a22121e3-62e1-4225-b67d-a7bb628e71e6">

## No Show Issue

Here, the active app is on the Studio Display (Screenshot is of MacBook)
<img width="1728" alt="Screenshot 2024-01-27 at 12 37 17 PM" src="https://github.com/Anze/KeyCluCask/assets/116489828/3e81d386-b993-4fa4-bb6c-d9ee54ed81e9">

## KeyClu Settings

<img width="832" alt="Screenshot 2024-01-27 at 12 46 44 PM" src="https://github.com/Anze/KeyCluCask/assets/116489828/3860b278-60fc-4abc-b597-94ffe510eea9">

**Comment by Anze** [comment]
Thanks for the screenshots! Can you tell if you moved the panel from a small screen to a bigger one or triggered it to show on the bigger screen? Also, was the bigger screen the "main" one when the panel was displayed?

**Comment by CMWalt** [comment]
You're welcome. For my test supplied the panel was initiated and remained on the "small" screen. 

I just tested moving the panel to the "large" screen, and the panel adjusted properly. This issue doesn't happen all the time.

**Comment by Anze** [comment]
Thanks for the info. Improving multi-monitor support is on my radar for the future.

**Comment by CMWalt** [comment]
I appreciate the response and great work on the app.

**Comment by CMWalt** [comment]
The issue with multiple monitors appears to be isolated to the "Desired Location" setting.

**Comment by Anze** [comment]
Hey [CMWalt](https://github.com/CMWalt),
I've just released a new version. Would love to hear your thoughts.

**Comment by CMWalt** [comment]
Hey Anze,

I haven't used the app much lately because I had problems making it fit my workflow. Now I'm on summer break from school; I see If I can fit it in. I’ll do my best ro send you some feedback.

Best regards,

Chris M. Walters
Major: B.A. International Studies
Minors: Economics | Science & Technology
Senior, The Ohio State University
***@***.******@***.***>
<https://aka.ms/o0ukef>
________________________________
