### ISSUE TITLE
Persistant Panel Doesn't Activate

### ISSUE THREAD

**Issue by CMWalt** [Anze/KeyCluCask#50]
With the new update, the Persistent Panel isn't working. I tried the trick of selecting "none" and then selecting the option to show it, but it isn't working this time.

**Comment by Anze** [comment]
Oh, thats strange why only this option have trouble. Can you please run this command in terminal and post output?
`defaults read com.0804team.KeyClu activationPersistentKeyType`

**Comment by CMWalt** [comment]
output = 1

**Comment by Anze** [comment]
Hey [CMWalt](https://github.com/CMWalt),
I've identified an issue, and it will be addressed in the upcoming release.

**Comment by Anze** [comment]
Hey [CMWalt](https://github.com/CMWalt),
New released is available now. Please let me know if you encounter any issues.

**Comment by CMWalt** [comment]
The persistent panel still doesn't show. Have you tested it using Mission Control?

**Comment by Anze** [comment]
That's a new factor to check out. Let me investigate it.
