### ISSUE TITLE
Panel does not activate, nor can the app be opened to configure it

### ISSUE THREAD

**Issue by RileyRetzloff** [Anze/KeyCluCask#52]
For some reason, the shortcut panel does not activate when double-tapping the command key. Further, I am unable to open the app by any method. I've used brew to uninstall and reinstall KeyClu several times but unfortunately it just won't work.

**Comment by RileyRetzloff** [comment]
On M1 Pro Macbook Pro.

**Comment by Anze** [comment]
Hey [RileyRetzloff](https://github.com/RileyRetzloff),
This issue could happend by many reasons. Here is the two that happens often:
1. It might be that you have denied permission to App when prompted. To resolve this issue, please follow these steps:
- Open `System Settings` on your macOS.
- Navigate to `Privacy & Security`.
- Go to the `Accessibility` section.

Check if KeyClu is listed in the list and ensure it turned on. If not, add app to the list and grant the required permissions. Restart the app.

2. It might be that you tapping `⌘` without holding it, please use this as reference: ![tap-tap-and-hold](https://raw.githubusercontent.com/Anze/KeyCluCask/bb9e3d6aed0a40295ed1ee2c6a0e131d76193caa/img/cmd-ani2.gif)

**Comment by RileyRetzloff** [comment]
Hi @Anze :)

Thanks so much for responding!

Unfortunately I'd already checked the Accessibility settings, and KeyClu is enabled. Sorry, should've mentioned that 😅

I'm also holding ⌘ down with the second keypress.

Still not quite sure exactly what's going wrong... one of my suspicions is that there might be some residual files from when I first uninstalled and reinstalled the app (`v0.18`) (which I did by simply moving it to trash, instead of using homebrew) that are now interfering with the current installation (`v0.19`) somehow. I could be totally wrong though.

I did try searching my entire mac for any files with the keyword `keyclu` after uninstalling the app using homebrew, but I didn't see any. I'm not sure about any other files with other names though.

Please let me know if there's any other info I can provide to help out! I really love your app the way you've built it out. Makes using my Mac so much easier and more fun :)

**Comment by jankal** [comment]
Hey everyone, I am encountering the same exact issue with the latest update. Everything worked fine before. Also tried reinstalling from Homebrew. - no change.

The app seems to launch perfectly right, but as soon as I either enter the shortcut (double-tap-and-hold Cmd) or try to open settings / any other option from the Menu Bar, the app quits.

I also checked with my Accessibility settings, unchecked and rechecked that toggle for KeyClu but to no avail...

**Comment by Anze** [comment]
Hey [jankal](https://github.com/jankal),
I apologize for the inconvenience you're facing. The upcoming release will address this issue. Thank you for understanding.

**Comment by 123heyitsmarie** [comment]
I have the exact same issue. Anzne, do you already know when the upcoming release will be published? :) Thank you!!

**Comment by RileyRetzloff** [comment]
Everything's working great for me!

Thanks Anze :)
