### ISSUE TITLE
[bug]: auto switch current window to desktop

### ISSUE THREAD

**Issue by AndrewDi** [Anze/KeyCluCask#60]
### Description

When trigger panel in Jetbrain software, after release, keyclu will auto switch current window to desktop

### Expected behavior

never auto switch

### App version

0.23.1

### macOS version

macOS Sonoma 14.4

### Installation method

Homebrew

### Checklist before submitting a bug

- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/Anze/KeyCluCask/issues) or [discussion](https://github.com/Anze/KeyCluCask/discussions).

**Comment by cofirazak** [comment]
Same here!
Solved this by:
1) brew uninstall --cask keyclu
2) Download the [latest version](https://github.com/Anze/KeyCluCask/releases/latest) .dmg
