### ISSUE TITLE
[bug]: Shortcuts/Persistent Panel shows KeyClu shortcuts instead of active application after search in shortcuts panel

### ISSUE THREAD

**Issue by danny-tps** [Anze/KeyCluCask#62]
### Description

Not sure if this was reported before, but if I trigger the shortcuts panel, trigger the search box via the shortcut key, then exit by pressing Esc, when I go to trigger the shortcuts panel again or the persistent panel, it shows me the KeyClu shortcuts instead of the current application's shortcuts.

I have to click inside the app's window to bring it into focus for the shortcuts panel to show the respective shortcuts again.

### Expected behavior

Opening the shortcuts panel again after having tried a search in the previous shortcuts panel should show the same application's shortcuts still.

### App version

0.23.1

### macOS version

macOS Sonoma 14.4

### Installation method

Homebrew

### Checklist before submitting a bug

- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/Anze/KeyCluCask/issues) or [discussion](https://github.com/Anze/KeyCluCask/discussions).

**Comment by Anze** [comment]
Hey [danny-tps](https://github.com/danny-tps),
I've noticed this behaviour, and it should been fixed in the latest version. Could you please update the app and see if the issue still persists?

**Comment by danny-tps** [comment]
works like a charm now. Thanks for the quick response!

**Comment by Anze** [comment]
Hey danny-tps,
Sorry to hear you're having troubles. To check the workflow I need some information from you: could you please share info, how you’ve set activation and the delay for holding the key? The most convenient way would be to provide a screenshot or copy-paste the output of a terminal command: defaults read com.0804Team.KeyClu.
