### ISSUE TITLE
Persistent panel is randomly triggered 

### ISSUE THREAD

**Issue by sazun** [Anze/KeyCluCask#63]
### Description

Hi. I am using Karabiner and BetterTouchTool for keyboard shortcuts and sometimes the persistent panel is unintendedly opened. I have not found a particular key combination that reliably opens it but it happens clearly without the 3 key presses. 
It had also happened to me with the shortcuts panel until setting the activation to pressing the command key twice. 

Anyway, I'd suggest adding the option of triggering the panels with a freely chosen keyboard shortcut, to better integrate KeyClu to different scenarios.

### Expected behavior

persistent panel only activate after pressing command key 3 times or with a eligible keyboard shortcut

### App version

0.24

### macOS version

macOS Sonoma 14.3.1 

### Installation method

Manual (dmg/zip)

### Checklist before submitting a bug

- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/Anze/KeyCluCask/issues) or [discussion](https://github.com/Anze/KeyCluCask/discussions).

**Comment by Anze** [comment]
Hi sazun,

Sorry to hear you're having troubles. To check the workflow I need some information from you: could you please share info, how you’ve set activation and the delay for holding the key? The most convenient way would be to provide a screenshot or copy-paste the output of a terminal command: defaults read com.0804Team.KeyClu.

**Comment by Anze** [comment]
Hi [sazun](https://github.com/sazun),
Since I didn't hear back from you, I went ahead and try to address the issue with the limited information available and enhanced the workflow. I can't guarantee it would work perfectly for your situation, but I gave it a shot.

**Comment by sazun** [comment]
Hi Anze,

Sorry for not responding before but I didn't catch your mail. Thanks a lot
for trying to fix the issue. I'll try it again and report back.

Regards.

**Comment by Anze** [comment]
Hi [sazun](https://github.com/sazun),
I've just released a new version. Could you please check if the issue has been resolved?
