### ISSUE TITLE
[feature]: Encourage Community Contributions to Support Display of Non-Menu Bar Shortcuts in KeyCluCask

### ISSUE THREAD

**Issue by tictaqqn** [Anze/KeyCluCask#67]
#### Objective
The main objective of this proposal is to enhance KeyCluCask by leveraging the power of open-source contributions to display a wider range of shortcuts, especially those not directly accessible from the menu bar. This initiative aims to create a vibrant, community-driven ecosystem around KeyCluCask, encouraging individuals to contribute shortcuts for various software, including but not limited to VSCode, Slack, Notion, and Linear.

#### Background
Users often face limitations due to the inability to display shortcuts that are not directly accessible from the menu bar.

#### Proposal
I propose the development of an open-source extension for KeyCluCask with the following key features:

1. **Extensible Shortcut Display:** This extension will enable KeyCluCask to display shortcuts not available through the standard menu bar, specifically catering to software such as VSCode, Slack, Notion, and Linear.

2. **Open Source Repository:** Establish a dedicated repository for this KeyCluCask extension. This repository will serve as a hub for community contributions, allowing anyone to contribute shortcuts for various software tools. This will facilitate the easy acceptance of new shortcuts and software.

#### Expected Impact
Implementing this feature will broaden the range of shortcuts that KeyCluCask can display. This community-led approach will ensure that KeyCluCask adapts and maintains its relevance to the evolving needs of its user base.

**Comment by Anze** [comment]
Hey [tictaqqn](https://github.com/tictaqqn),

Thanks for the idea! The app already have built-in functionality for adding and displaying such shortcuts, if the hotkey isn't showing in the menu. You can access this feature in the `Settings` -> `My Shortcuts`. Additionally, there are options to export/import these shortcuts as files per application, making it easy to share them with others. To display such shortcuts (always at last column) is also required to enable "My Shortcuts" option in `Integrations` Settings. I hope this is what your needs. Additionally, there's a way to exclusively display "Global" shortcuts defined using "My Shortcuts." However, this option requires a different trigger for display than simply holding the ⌘ key.

Regarding the second part, my idea was to create a dedicated space to store these files, and your suggestion to have it as another repository is actually great.

**Comment by tictaqqn** [comment]
Thanks for explaining how to share the shortcuts.
I hope for a future where these files can be shared like extensions through repositories.

**Comment by Anze** [comment]
Hey [tictaqqn](https://github.com/tictaqqn),

I've created the repository as you suggested. You can find it here: [KeyClu Extensions](https://github.com/Anze/KeyCluExtensions). I've also added a few files to get started. Feel free to check them out in the repository.

**Comment by tictaqqn** [comment]
Great! Thx!
