### ISSUE TITLE
[feature]: View Only Bookmarked Keystrokes

### ISSUE THREAD

**Issue by wanwindwalker** [Anze/KeyCluCask#68]
### Proposal

A way to show only bookmarked keystrokes to filter through apps with a lot of keystrokes and make it easier to find them. Perhaps holding shift or option after calling out the overlay? And for the persisting overlay perhaps add a button in the top right that hides non bookmarked keystrokes. I'm just not keen on hiding keystrokes one by one instead, I might need them. Something like what i described may be a nice quality of life feature.

**Comment by whisterlee** [comment]
Whether bookmarks can be prioritized？

**Comment by Anze** [comment]
Hey [whisterlee](https://github.com/whisterlee),
Are you suggesting implementing feature more quickly, or simply prioritizing the display of bookmarked items?

**Comment by whisterlee** [comment]
Thank you for considering my suggestion. Would it be possible to temporarily avoid refreshing the layout when toggling the bookmark status, and then refresh the layout the next time it's viewed?

**Comment by Anze** [comment]
Haven't thought about this in that way, but it sounds like it could work. I'll give it a try.

**Comment by Anze** [comment]
It doesn't quite match the initial vision. I've made few screenshots showcasing various alternatives. Take a look and let me know your thoughts. I'm unsure if it looks good or not.

1. Normal look
<img width="1582" alt="Screenshot 2024-04-16 at 01 32 04" src="https://github.com/Anze/KeyCluCask/assets/38272/0827f1e9-9f25-4efa-be64-32f58dcb1e96">

2. Bookmarks takes first column
<img width="1582" alt="Screenshot 2024-04-16 at 01 31 51" src="https://github.com/Anze/KeyCluCask/assets/38272/efe3c8f9-dadf-4bb5-9698-b4e8a19d218c">
<img width="1582" alt="Screenshot 2024-04-16 at 01 30 50" src="https://github.com/Anze/KeyCluCask/assets/38272/3482fae6-d4ec-4774-a081-84ad0674aa4f">

3. Bookmarks takes last column
<img width="1582" alt="Screenshot 2024-04-16 at 02 13 47" src="https://github.com/Anze/KeyCluCask/assets/38272/62695f5c-183c-4829-bc0e-b64f1091100e">

**Comment by whisterlee** [comment]
Your idea is even more thoughtful! Based on my personal usage habits, I prefer the third option, as I don't have many keyboard shortcuts for bookmarking. I just want to quickly remember this shortcut. I wonder if other users have the same usage scenario as me.

**Comment by wanwindwalker** [comment]
I think the best way to do it is displayed in image 2 b, however make it so there's no unnecessary empty space by rolling out the rest of the categories immideatly after Bookmarks. I'm also not sure if it would be better to keep Bookmarked hotkeys in both the Bookmarks section and where they are originally from so you can know where to find them in the top navigation bar.

**Comment by Anze** [comment]
After reviewing request (#69), I realized that displaying only bookmarked items may not be necessary. Instead, it might suffice to show them either at the beginning or end of the list. This approach maintains visibility while reducing complexity in the user interface.
What do you think?

![Image](https://github.com/Anze/KeyCluCask/assets/38272/4902dfda-59e1-497b-a2c8-79a41913a375)

![Image](https://github.com/Anze/KeyCluCask/assets/38272/b905bf59-b909-4ad5-afcd-9c4e33069d64)

**Comment by huyz** [comment]
I think that my suggestion at https://github.com/Anze/KeyCluCask/issues/65 would be able this request.

I just want to have toggles (yes, it'd be ok for me to use the mouse for these operations) to choose what to show/hide (and the toggles would persist).
