### ISSUE TITLE
White lines and layout shift when scrollbar is necessary

### ISSUE THREAD

**Issue by weisJ** [Anze/KeyCluCask#7]
If a scrollbar is necessary due to many items (e.g. in Xcode) the scrollbar appears with a delay causing some layout shift.
Also white lines are visible between some columns in this case (in Xcode with 4 columns it is before the third and fourth column)

**Comment by Anze** [comment]
Hey hey,
Can you provide more details please:
- macOS version
- screen resolution / display settings

At the moment i know that scrollbar looks ugly in Sonoma and plan to work on it.

**Comment by weisJ** [comment]
macOS: 13.4.1 (c) (22F770820d)
Screen Resolution: 2560 x 1440

Here is a recording of what I mean:
https://dropover.cloud/f40f22

**Comment by Anze** [comment]
I've tried to fix issue with another approach of presenting window. Atm it is in v0.8, but it might be not stable enough. Please check if the issue is fixed.

**Comment by weisJ** [comment]
It looks a lot better now. However sometimes the activation seems to be a bit funky. Also neither button in the automatic update dialog do anything an I can't dismiss the dialog.

On another note it would be nice to be able to hide the bar at the bottom with the settings. I think it looks a lot cleaner without it.

**Comment by Anze** [comment]
Yeah, i know about this thingy with autoupdate (disabled it by default now). Unfortunately i need to show that bottom line because this is the only way to get to the settings when you choose to hide icon in menubar.

**Comment by weisJ** [comment]
How about opening the settings when KeyClu (the application not the shortcut) is opened again while already open? Also I noticed that the border on the bottom bar has a different colour from the dividers.

**Comment by Anze** [comment]
Thats an interesting approach. But I think its for devs and normal users would not expect this behaviour.

**Comment by weisJ** [comment]
For reference apps like Bartender or HiddenBar employ the same technique? Maybe only show the bar if the menubar icon is hidden. Or make hiding the bottom optional with a not on how to go to the settings in this case?

**Comment by Anze** [comment]
I've made option to hide credits if you do not like it. Also if you hide app icon in menubar now you can call settings with just pressing ⌘ 3 times.
