### ISSUE TITLE
[feature]: rename Bookmarks to Starred/Favorites

### ISSUE THREAD

**Issue by huyz** [Anze/KeyCluCask#70]
### Proposal

When I see Bookmarks I always think of Web Browser bookmarks.  It's quite confusing to users to have 2 meanings.

Indeed the settings use both meanings:
![screenshot 2024-04-26T083553Z@2x](https://github.com/Anze/KeyCluCask/assets/128394/4b3a18dc-a2e3-4a1c-94ee-3002fc1d2547)
![screenshot 2024-04-26T083626Z@2x](https://github.com/Anze/KeyCluCask/assets/128394/179bcd88-ea20-43ae-be2d-7890b1fb92c3)

I suggest that KeyClub stop using the term "bookmarks" and instead use the common alternatives: "starred", "favorites", "pinned", etc.

**Comment by Anze** [comment]
Hey [huyz](https://github.com/huyz),
I can change the icon to a star. When it comes to the action labels, I'm struggling to finding the right words for "Add to favorites" and "Remove from favorites". Personally, I prefer the simplicity of "Bookmark" and "Unbookmark" due to their simplicity and single-word format. Please note that every option in the menu consists of a single word for the call-to-action. Would you be up for giving some great alternatives?

**Comment by huyz** [comment]
@Anze Common words for that are the verbs "star" and "unstar" if you just want single words that parallel "bookmark" and "unbookmark". Or "favorite" and "unfavorite". These nouns are commonly converted to verbs.


For example, Slack has:
![screenshot 2024-05-01T084439Z@2x](https://github.com/Anze/KeyCluCask/assets/128394/0f7a1e0f-1101-4780-8e63-6b1239bda209)

![screenshot 2024-05-01T084122Z@2x](https://github.com/Anze/KeyCluCask/assets/128394/c8063d05-78a5-40d7-84a6-fdf963720748)

For comparison, some samples of other apps I use today are wordier:

- Gmail
![screenshot 2024-05-01T084741Z@2x](https://github.com/Anze/KeyCluCask/assets/128394/20056b82-de11-4ec3-a4ec-cbee2e0cf2e8)


- Notion
![screenshot 2024-05-01T083757Z@2x](https://github.com/Anze/KeyCluCask/assets/128394/68b41b84-bd7d-403d-8c5e-659354ae3483)

- Linear
![screenshot 2024-05-01T083832Z](https://github.com/Anze/KeyCluCask/assets/128394/4a1dfc08-124b-4d16-bdc4-d0e2e91de892)

**Comment by huyz** [comment]
An exact use by Atlassian Confluence of "star"/"unstar":
![screenshot 2024-05-01T085754Z@2x](https://github.com/Anze/KeyCluCask/assets/128394/e746b58b-a384-4920-b2b3-fa986a492ff2)
![screenshot 2024-05-01T085801Z@2x](https://github.com/Anze/KeyCluCask/assets/128394/896066d1-0829-4110-ace1-dab43a1cc00f)
