### ISSUE TITLE
[bug]: Highlights are wrong when using Hyperkey

### ISSUE THREAD

**Issue by leoravagnani** [Anze/KeyCluCask#75]
### Description

I use [Hyperkey](https://hyperkey.app) to turn my Caps Lock into a combination of Ctrl+Opt+Shift+Cmd.

When I press the hyperkey KeyClu highlights shortcuts as if I have only Cmd pressed. Pressing all modifiers separately works as expected.

https://github.com/Anze/KeyCluCask/assets/13058201/f39347de-692d-49ca-a762-51c34c5273d8

### Expected behavior

Highlight shortcuts as if all modifiers are being pressed.

### App version

0.26

### macOS version

macOS Sonoma 14.4.1

### Installation method

Manual (dmg/zip)

### Checklist before submitting a bug

- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/Anze/KeyCluCask/issues) or [discussion](https://github.com/Anze/KeyCluCask/discussions).

**Comment by Anze** [comment]
Hey [leoravagnani](https://github.com/leoravagnani),
While I'm investigating the issue, could you please share a screenshot of the settings for Hyperkey to assist in identifying the problem?

**Comment by leoravagnani** [comment]
Hey @Anze, there you go
![Screenshot 2024-04-27 at 12 06 44](https://github.com/Anze/KeyCluCask/assets/13058201/27cbf875-ea3a-4d57-aed0-955da818a49c)

**Comment by Anze** [comment]
Thanks for providing the screenshot.
I've discovered that the Hyperkey functions in this manner: when Caps lock is "remapped physical key to hyper key caps lock", it's actually mapped Caps lock key to the Command key (left one) only. The other modifier keys are _applied_ only the moment you press a non-modifier key (referred as keypresses) or when you click, etc.
The Hyperkey app doesn't hold/press all the modifier keys when Caps lock is pressed.
Unfortunately, it is outside the scope of the app to monitor such simulated "keypresses".

**Comment by Anze** [comment]
I'll try a different approach to monitor the keys and see if it make any improvements. Currently, other apps like KeyCastr also struggle to identify the correct keys, but KeyCodes manages to do so.

**Comment by leoravagnani** [comment]
I had no clue whatsoever how Hyperkey does what it does, nice insight there.

I just tried setting up the hyperkey through Karabiner-Elements and highlights work correctly! I'll stick to it as I was already about to explore some other things such as customizing right-side modifiers as they go mostly unused.

Could be worth looking into a fix for Hyperkey but it seems Karabiner is a better alternative altogether given the feature set.

**Comment by Anze** [comment]
It appears that CGEvent (old) doesn't handle it the same way as NSEvent (new). I'll investigate and find a workaround. Although I transitioned from NSEvent to CGEvent for better control over event propagation, it seems that CGEvent might not be able to handle the necessary case. Nonetheless, I'll continue to explore it, as NSEvent has proven to be more stable in operation.

**Comment by leoravagnani** [comment]
@Anze just got a new [Hyperkey update](https://hyperkey.app/versions) and it seems to fix just what you're reporting. Makes me wonder if the dev is watching this thread haha

> 0.34
> Fixed an issue where certain scenarios had the potential to result in a stuck hyperkey

**Comment by Anze** [comment]
Hey [leoravagnani](https://github.com/leoravagnani),
I've just released a new version. Now should be working. There are still some uncertainties in the workflow when pressing Caps Lock and Command.

**Comment by leoravagnani** [comment]
Hi @Anze, I moved on from HyperKey to Karabiner because I needed more custom combinations and everything seems to be working fine! Thanks for taking your time to look into this though, I'm sure it will benefit many others!

**Comment by gldtn** [comment]
Just thought I would give some feedback, It is working Superkey(https://superkey.app/) which is by the same author. Basically a paid version of Hyperkey.
