### ISSUE TITLE
[feature]: customize shortcuts

### ISSUE THREAD

**Issue by ariccb** [Anze/KeyCluCask#81]
### Proposal

for me, i've got a custom keyboard that has enter on hold for my cmd key, making it impossible to activate the double-click-and-hold functionality to trigger the shortcuts. Similarly, for the persistent shortcut window the only option is triple clicking cmd, which is impossible for me since "tapping" my cmd key sends an "enter" keystroke not a "cmd" keystroke. 

having more options for which key activates the tool, or even customizing the shortcut by recording a shortcut would be awesome.

**Comment by Anze** [comment]
Hey [ariccb](https://github.com/ariccb),
Thank you for the suggestion. I'll consider implementing it in a future.

**Comment by subsy** [comment]
I just created an issue for the same sorry - this makes KeyClu unusable unfortunately. Hope this is something you can implement @Anze 🙌
