### ISSUE TITLE
[feature]: Custom global hotkeys

### ISSUE THREAD

**Issue by subsy** [Anze/KeyCluCask#87]
### Proposal

I use a ZSA voyager keyboard with homerow mods (so I invoke Cmd by holding my A key).
I'm unable to get the shortcuts panel to display.
I would like to be able to configure custom hotkeys to launch the shortcuts and persistent panels.

**Comment by Anze** [comment]
Hey [subsy](https://github.com/subsy),
I've just released a new version. I hope this customization meets your needs.
