### ISSUE TITLE
[feature]: Finder missing "Command + Shift + ." (Period)

### ISSUE THREAD

**Issue by oxoocoffee** [Anze/KeyCluCask#91]
### Proposal

I noticed on latest version there is no shortcut for hide/unhide hidden files and folders (that starts with ".")

### Alternatives

Please add it in next update

**Comment by Anze** [comment]
Hey [oxoocoffee](https://github.com/oxoocoffee),

KeyClu only displays menu items that are part of the actual menu. Unfortunately, the "Show/Hide Hidden Files" option is a hotkey and isn't listed in Finder's menu. To help with this, the app has a "My Shortcuts" section where you can register any missing shortcuts for specific apps. You can also explore [KeyCluExtensions](https://github.com/Anze/KeyCluExtensions), where existing extensions can help you add missing shortcuts for other apps. Just don't forget to enable listing under "Integration" -> "My Shortcuts".
