### ISSUE TITLE
[bug]: skhd integration not showing

### ISSUE THREAD

**Issue by sziyan** [Anze/KeyCluCask#94]
### Description

Enabling skhd integration in Keyclu integrations tab (and refreshing) with the following line in skhdrc file is not showing skhd shortcuts in Keyclu:

```
# open qutebrowser
cmd + shift - return : ~/Scripts/qtb.sh
```

Troubleshooting performed:
- Revert to version 0.26 (no luck)
- Created a new skhdrc file and adding only above line into the file (no luck)
- Restart skhd service (no luck)

### Expected behavior

Defined skhdrc keyboard shortcuts show up in KeyClu

### App version

0.27

### macOS version

macOS Sonoma 14.6.1

### Installation method

Manual (dmg/zip)

### Checklist before submitting a bug

- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/Anze/KeyCluCask/issues) or [discussion](https://github.com/Anze/KeyCluCask/discussions).

**Comment by Anze** [comment]
Hey [sziyan](https://github.com/sziyan),
Sorry to hear you're having troubles. Can you please check if file placed at location mentioned [here](https://github.com/Anze/KeyCluCask/wiki/Integrations-%E2%80%90-skhd)?

**Comment by sziyan** [comment]
> Hey [sziyan](https://github.com/sziyan), Sorry to hear you're having troubles. Can you please check if file placed at location mentioned [here](https://github.com/Anze/KeyCluCask/wiki/Integrations-%E2%80%90-skhd)?

thanks for the reply! Yes, my skhd file is in `$HOME/.config/skhdrc`

**Comment by gldtn** [comment]
@sziyan you need to format it like this:

```
#KeyClu[Qutebrowser]: Open browser
cmd + shift - return : ~/Scripts/qtb.sh
```

You can look at my config here: https://github.com/gldtn/dotfiles/blob/main/skhd/skhdrc

**Comment by sziyan** [comment]
> @sziyan you need to format it like this:
> 
> ```
> #KeyClu[Qutebrowser]: Open browser
> cmd + shift - return : ~/Scripts/qtb.sh
> ```
> 
> You can look at my config here: https://github.com/gldtn/dotfiles/blob/main/skhd/skhdrc

I created a new file with your config and place it in `$HOME/.config/skhd/skhdrc` but skhd mapping is still not showing up.

Is there any other configurations need to be done?

**Comment by gldtn** [comment]
I was trying out another WM(Aerospace) so I did not know there was a bug with Keyclu integration and SKHD. I just went back to Yabai & Skhd and it's not showing for me as well. Seems like @Anze is working on the issue though.

**Comment by Anze** [comment]
Hey guys,
New released is available now. Please let me know if you still encounter this issue.

**Comment by gldtn** [comment]
> Hey guys, New released is available now. Please let me know if you still encounter this issue.

Everything is working on my end. Thanks for the fix @Anze
