### ISSUE TITLE
[bug]: iEmpty window at startup under macOS 15

### ISSUE THREAD

**Issue by det-box** [Anze/KeyCluCask#96]
### Description

Under macOS 15, an empty window appears on startup.
<img width="900" alt="Bildschirmfoto 2024-09-18 um 20 23 35" src="https://github.com/user-attachments/assets/e24cb1da-6dc6-47a7-bb45-0cecf879e6f4">

### App version

0,27

### macOS version

macOS 15

### Installation method

Manual (dmg/zip)

### Checklist before submitting a bug

- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/Anze/KeyCluCask/issues) or [discussion](https://github.com/Anze/KeyCluCask/discussions).

**Comment by Anze** [comment]
Hey [det-box](https://github.com/det-box),
Thanks for reporting the bug! I'm already aware of it, but I can't verify it just yet due to troubles with installing macOS 15. Once everything's up and running, I'll handle it right away.

**Comment by DaSNyB** [comment]
No news about this bug?

**Comment by det-box** [comment]
Hi,
Thanks, works wonderfully. 
You are the best.
