### ISSUE TITLE
[bug]: "KeyClu" not responding upon opening.

### ISSUE THREAD

**Issue by MariusNielsen** [Anze/KeyCluCask#97]
### Description

When I try to open KeyClu after updating to 0.28 the app no longer works and I get a report saying "You can't open the application "KeyClu" because it is not responding." from MacOs.

### App version

0.28

### macOS version

Sonoma 14.5

### Installation method

Homebrew

### Checklist before submitting a bug

- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/Anze/KeyCluCask/issues) or [discussion](https://github.com/Anze/KeyCluCask/discussions).

**Comment by Anze** [comment]
Hey [MariusNielsen](https://github.com/MariusNielsen),
Thanks for reporting the issue. I wasn't able to replicate it, at least in a virtual machine environment. Still, you can try the following steps to resolve it:
- force quit the app using the "Activity Monitor" utility.
- restart your Mac.
- reinstall the app.
Let me know if that helps!

**Comment by MariusNielsen** [comment]
Thank you this worked.
