### ISSUE TITLE
[bug]: Unable to retrieve and display Steam shortcut keys correctly

### ISSUE THREAD

**Issue by HXavier21** [Anze/KeyCluCask#99]
### Issue:
When trying to launch Keyclu within Steam, the shortcut keys list for Steam is not retrieved or displayed correctly in the UI. Instead of showing Steam's shortcuts, it displays the Steam Helper's shortcut list, which appears to be empty.

### Steps to reproduce:
1. Open Steam.
2. Launch Keyclu.
3. Attempt to view Steam shortcut keys.

### Expected result:
Keyclu should retrieve and display the correct Steam shortcut keys in the UI.

### Actual result:
The shortcut keys list displayed is from Steam Helper, and it is empty.

### Additional information:
- OS: [MacOS 14.7 aarch64 M2]
- Keyclu version: [0.28(22732)]
- Steam version: [1726604483]

Please let me know if further details or logs are needed to investigate the issue. Thank you!

### App version

0.28

### macOS version

14.7

### Installation method

Homebrew

### Checklist before submitting a bug

- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/Anze/KeyCluCask/issues) or [discussion](https://github.com/Anze/KeyCluCask/discussions).

**Comment by Anze** [comment]
Hey [HXavier21](https://github.com/HXavier21),
Thanks for reporting the issue. I'll look into the possibility of improving the behavior for this case.

**Comment by HXavier21** [comment]
I think at least the set shortcut keys (cmd + ,) should be displayed. The main issue is actually that it displays Steam Helper instead of Steam.🤧

**Comment by Anze** [comment]
Hey [HXavier21](https://github.com/HXavier21),
I've just released a new version. Please check if it works for you now.

**Comment by HXavier21** [comment]
> Hey [HXavier21](https://github.com/HXavier21), I've just released a new version. Please check if it works for you now.

Yes, it works properly! Thanks so much! 😘
